### ISSUE TITLE
githubの登録の罠

### ISSUE THREAD

**Issue by kankyouhakai** [tsubame-rustica/Frontend#15]
READMEのSSH接続の章でid_git_rsaという名前で鍵を作成するとうまくいかない．
実際にssh接続する際に「id_rsa」，「id_dsa」，「identity」という名前のファイルをデフォルトで参照するようになっているため`ssh -T git@github.com`を実行した際に"Permission denited"が出る．

鍵の名前を変更するかconfigファイルを作ることで解決できる

**Comment by tsubame-rustica** [comment]
すみませんでした。`id_rsa`に変更しておきます。

**Comment by kankyouhakai** [comment]
[GitHubでssh接続する手順\~公開鍵・秘密鍵の生成から\~](https://qiita.com/shizuma/items/2b2f873a0034839e47ce)

**Comment by kankyouhakai** [comment]
リモート接続をしてpushするの章で`git remote add [URL]`となっているが``git remote add origin [URL]``とするのが正しい．

**Comment by tsubame-rustica** [comment]
すみません。修正しておきます。

**Comment by tsubame-rustica** [comment]
修正完了
